import { useEffect, useRef, useState } from 'react';

export default function LyricsPanel({
  song, activeLyricIdx, introSecsRemaining,
  isPlaying, currentSec, lyricOffset, onSetLyricOffset,
  onSeek, isFav, onToggleFav, onOpenSpotify, onCopy,
  onBackToResults,
}) {
  const [fontSize, setFontSize] = useState(16);
  const activeRef = useRef(null);
  const containerRef = useRef(null);

  // Auto-scroll to active line when it changes
  useEffect(() => {
    if (activeLyricIdx >= 0 && activeRef.current) {
      activeRef.current.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
    if (activeLyricIdx === 0 && containerRef.current) {
      containerRef.current.scrollTop = 0;
    }
  }, [activeLyricIdx]);

  if (!song) return null;

  const isIntro = activeLyricIdx === -1;
  const firstLyricTime = song.lyrics?.[0]?.t || 0;

  // "Mark singing started here" — calculates the offset needed so the
  // first lyric becomes active right now, at the current playback position.
  // This is the fix for videos whose actual intro length differs from
  // what LRCLIB's timestamps assume (different upload, edit, etc.)
  const handleMarkSingingStarted = () => {
    const neededOffset = firstLyricTime - currentSec;
    onSetLyricOffset(Math.round(Math.max(-60, Math.min(60, neededOffset))));
  };

  return (
    <div className="lyrics-panel">

      {/* Song header */}
      <div className="song-header">
        {onBackToResults && (
          <button
            className="btn-icon-sm back-btn"
            onClick={onBackToResults}
            title="Back to search results"
          >
            <i className="ti ti-arrow-left" />
          </button>
        )}
        <div className="album-art">
          <i className="ti ti-music" />
        </div>
        <div className="song-meta">
          <h2 className="song-title">{song.title}</h2>
          <p className="song-artist">{song.artist}</p>
          <div className="song-badges">
            <span className="badge badge-purple">{song.genre || 'Music'}</span>
            <span className="badge badge-gray">{song.year || '—'}</span>
            {song.aiGenerated && (
              <span className="badge badge-ai" title="Lyrics generated by Claude AI — may not be word-perfect">
                ✨ AI lyrics
              </span>
            )}
          </div>
        </div>
        <div className="song-actions">
          <button className="btn-outline" onClick={onOpenSpotify}>
            <i className="ti ti-brand-spotify" /> Listen
          </button>
          <button className="btn-icon-sm" onClick={onToggleFav} title="Favourite">
            <i
              className={`ti ${isFav ? 'ti-heart-filled' : 'ti-heart'}`}
              style={{ color: isFav ? '#E24B4A' : undefined }}
            />
          </button>
        </div>
      </div>

      {/* Lyrics header */}
      <div className="lyrics-header">
        <span className="lyrics-label">Lyrics</span>
        <div className="lyrics-controls">
          <button className="btn-icon-sm" onClick={() => setFontSize(s => Math.max(12, s - 1))} title="Smaller">A−</button>
          <button className="btn-icon-sm" onClick={() => setFontSize(s => Math.min(24, s + 1))} title="Larger">A+</button>
          <button className="btn-icon-sm" onClick={onCopy} title="Copy lyrics">
            <i className="ti ti-copy" />
          </button>
        </div>
      </div>

      {/* Intro banner — shown while song plays but lyrics haven't started */}
      {isPlaying && isIntro && (
        <div className="intro-banner">
          <div className="intro-banner-row">
            <div className="intro-dots"><span /><span /><span /></div>
            <p className="intro-text">
              {introSecsRemaining > 0 ? `Lyrics start in ${introSecsRemaining}s` : 'Intro…'}
            </p>
            {firstLyricTime > 0 && (
              <button className="intro-skip" onClick={() => onSeek(firstLyricTime)}>
                Skip to lyrics ›
              </button>
            )}
          </div>

          {/* Shown once the countdown looks long enough to suggest a mismatch — 
              nudges the user toward the fix instead of just waiting */}
          {introSecsRemaining > 15 && (
            <div className="intro-mismatch-hint">
              <i className="ti ti-alert-triangle" />
              <span>If the singer has already started, this video's intro may differ from the lyric timing.</span>
              <button className="intro-mismatch-fix" onClick={handleMarkSingingStarted}>
                <i className="ti ti-target-arrow" /> Singing started — sync now
              </button>
            </div>
          )}
        </div>
      )}

      {/* Lyric sync offset is active — small persistent indicator */}
      {lyricOffset !== 0 && (
        <div className="sync-indicator">
          <i className="ti ti-adjustments-horizontal" />
          Lyrics shifted {lyricOffset > 0 ? `+${lyricOffset}s` : `${lyricOffset}s`}
          <button className="sync-indicator-reset" onClick={() => onSetLyricOffset(0)}>Reset</button>
        </div>
      )}

      {/* Manual lyrics search link — shown when no real lyrics were found */}
      {song.duration === 0 && (
        <div className="no-lyrics-help">
          <a
            href={`https://www.google.com/search?q=${encodeURIComponent(song.title + ' ' + song.artist + ' lyrics')}`}
            target="_blank" rel="noreferrer"
            className="no-lyrics-link"
          >
            <i className="ti ti-search" /> Search lyrics on the web
            <i className="ti ti-external-link" />
          </a>
        </div>
      )}

      {/* Lyric lines — scrolls independently, page never moves */}
      <div className="lyrics-container" ref={containerRef}>
        {(song.lyrics || []).map((line, i) => {
          const isActive = i === activeLyricIdx;
          const isPast = activeLyricIdx >= 0 && i < activeLyricIdx;
          const isNear = !isActive && Math.abs(i - activeLyricIdx) === 1;

          return (
            <div
              key={i}
              ref={isActive ? activeRef : null}
              className={[
                'lyric-line',
                isActive ? 'active' : '',
                isPast ? 'past' : '',
                isNear ? 'near' : '',
              ].filter(Boolean).join(' ')}
              style={{ fontSize: isActive ? fontSize + 3 : fontSize }}
              onClick={() => onSeek(line.t)}
            >
              {line.l || <span className="lyric-spacer">♪</span>}
            </div>
          );
        })}
      </div>
    </div>
  );
}